### ISSUE TITLE
ProtocolError raised when used in flexible environments w/custom runtime

### ISSUE THREAD

**Issue by eric-optimizely** [GoogleCloudPlatform/httplib2shim#3]
I just tried this code with `gcloud==0.12.1` in my Flask app that's running in a custom runtime of the flexible environments (formerly managed vms). I'm using the `.patch()` method and calling it before any of my code runs. The following is the traceback that I see.

```
Traceback (most recent call last):
  File "/env/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/env/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/env/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/env/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/env/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vmagent/app/backend/application/indexing/views.py", line 380, in index_sequential_backup_file
    fp = _open_gcs_file(bucket, filename)
  File "/home/vmagent/app/backend/application/indexing/views.py", line 74, in _open_gcs_file
    bucket = gcs_client.get_bucket(bucket_name)
  File "/env/local/lib/python2.7/site-packages/gcloud/storage/client.py", line 167, in get_bucket
    bucket.reload(client=self)
  File "/env/local/lib/python2.7/site-packages/gcloud/storage/_helpers.py", line 77, in reload
    _target_object=self)
  File "/env/local/lib/python2.7/site-packages/gcloud/connection.py", line 339, in api_request
    target_object=_target_object)
  File "/env/local/lib/python2.7/site-packages/gcloud/connection.py", line 240, in _make_request
    return self._do_request(method, url, headers, data, target_object)
  File "/env/local/lib/python2.7/site-packages/gcloud/connection.py", line 269, in _do_request
    body=data)
  File "/env/local/lib/python2.7/site-packages/oauth2client/client.py", line 597, in new_request
    self._refresh(request_orig)
  File "/env/local/lib/python2.7/site-packages/oauth2client/client.py", line 863, in _refresh
    self._do_refresh_request(http_request)
  File "/env/local/lib/python2.7/site-packages/oauth2client/client.py", line 895, in _do_refresh_request
    self.token_uri, method='POST', body=body, headers=headers)
  File "/env/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1609, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/env/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1351, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/env/local/lib/python2.7/site-packages/httplib2shim/__init__.py", line 133, in _conn_request
    raise _map_exception(e)
ProtocolError: ('Connection aborted.', BadStatusLine("''",))"   
```

**Comment by theacodes** [comment]
Thanks for reporting. Do you get this same issue when running locally?

**Comment by eric-optimizely** [comment]
I haven't tried it locally, but it would be in a Docker container and I'm not certain how the Google SDKs handle the differences.  Do you expect that it would work locally but has bugs in production?

**Comment by theacodes** [comment]
gcloud-python itself doesn't care where you run. oauth2client does, but only in terms of what auth methods it tries.

I would expect the same error locally, docker container or not. If you can reproduce locally, it'll help us debug exactly what's going on.

**Comment by eric-optimizely** [comment]
Well, I spent a couple hours trying to get it to run locally but ended up hitting failures where the runtime tries to connect to Google's internal hostnames [like this one](https://github.com/GoogleCloudPlatform/python-compat-runtime/blob/2791292e0abeeeefda4ba8c37d36491be887cd84/appengine-compat/exported_appengine_sdk/google/appengine/ext/vmruntime/vmconfig.py#L23).

I'm not sure where to go from here because there's really [no documentation for running these locally](https://cloud.google.com/appengine/docs/flexible/custom-runtimes/quickstart#running_hello_world_on_your_local_machine).

**Comment by theacodes** [comment]
Ah, you're using compat - compat explicitly can't be run locally.

Hmm. Can you try just running that piece of code locally without all of your other app stuff? e.g, make a minimal case to reproduce the bug?

**Comment by eric-optimizely** [comment]
Seems to work locally.

**Comment by eric-optimizely** [comment]
Regarding compat: Would you mind asking someone from that team to update the docs to make it clear that it's not possible to run it locally? I wasted a lot of time trying and it would have been great to know that upfront.

**Comment by theacodes** [comment]
You can run your app locally just not the full runtime, see [here](https://cloud.google.com/appengine/docs/flexible/python/migrating-an-existing-app#running_locally).

**Comment by theacodes** [comment]
So, I'm interested in seeing where the compat runtimes causes this issue. Can you let me know if you got your application running under dev_appserver? And if so, can you tell me if the issue is present when using dev_appserver?

**Comment by theacodes** [comment]
Closing this due to inactivity and due to the fact that the compat runtimes are now deprecated.
